### ISSUE TITLE
Save location for Windows

### ISSUE THREAD

**Issue by iamgreaser** [AlanDeSmet/TIS-100-Hackers-Guide#1]
While I'm still working out how to make both Linux Steam and TIS-100 behave properly I'm running the Windows versions.

The path is at `$(HOME)/My Games/TIS-100/$(USERID)/` and has the save and save.dat things in it. The "My Games" directory is probably in `My Documents` - failing that, it's in `C:\users\$(USERNAME)\`.

Someone else might want to confirm that on an actual Windows machine.

Enjoy.

**Comment by jack980517** [comment]
I'm playing it on Windows and wrote the path on pull request #2.

**Comment by AlanDeSmet** [comment]
Thanks iamgreaser for noting this. Thanks jack980517 for offering the pull request. It should be fixed now.
